import Head from "next/head";
import Image from "next/image";
import { Pagination, Post, Sidebar } from "../components";

import { PostLayout } from "../layouts/PostLayout";

const items = [
  {},
  {},
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <PostLayout>
        <div className="posts">
          {items.map((obj: any) => (
            <Post key={obj.id} {...obj} />
          ))}
        </div>
        <Pagination />
      </PostLayout>
    </div>
  );
}
